apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: django-polls-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: django-polls-service
          servicePort: 8000
